// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Trend.MudWeb.Models;

public partial class CompetitorPost
{
    public int PostId { get; set; }

    public int? CompetitorId { get; set; }

    public string PostUrl { get; set; }

    public double? EngagementRate { get; set; }

    public DateTime? PostedAt { get; set; }

    public virtual Competitor Competitor { get; set; }
}