// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Trend.MudWeb.Models;

public partial class Competitor
{
    public int CompetitorId { get; set; }

    public int? UserId { get; set; }

    public string AccountHandle { get; set; }

    public string Platform { get; set; }

    public DateTime? LastScrapedAt { get; set; }

    public virtual ICollection<CompetitorPost> CompetitorPosts { get; set; } = new List<CompetitorPost>();

    public virtual User User { get; set; }
}