// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Trend.MudWeb.Models;

public partial class ContentRecommendation
{
    public int RecommendationId { get; set; }

    public int? TrendId { get; set; }

    public string SuggestedHook { get; set; }

    public string SuggestedCta { get; set; }

    public bool? IsPremiumOnly { get; set; }

    public virtual SocialTrend Trend { get; set; }
}