// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Trend.MudWeb.Models;

public partial class Nich
{
    public int NicheId { get; set; }

    public string NicheName { get; set; }

    public virtual ICollection<SocialTrend> SocialTrends { get; set; } = new List<SocialTrend>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}