// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Trend.MudWeb.Models;

public partial class SocialTrend
{
    public int TrendId { get; set; }

    public string Platform { get; set; }

    public string TrendType { get; set; }

    public string TrendName { get; set; }

    public int? NicheId { get; set; }

    public double? GrowthScore { get; set; }

    public bool? IsViral { get; set; }

    public DateTime? DiscoveredAt { get; set; }

    public virtual ICollection<ContentRecommendation> ContentRecommendations { get; set; } = new List<ContentRecommendation>();

    public virtual Nich Niche { get; set; }

    public double GrowthScoreValue => Convert.ToDouble(GrowthScore);

}