// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Trend.MudWeb.Models;

public partial class TrendContext : DbContext
{
    public TrendContext(DbContextOptions<TrendContext> options)
        : base(options)
    {
    }

    // --- DB SETS ---
    // Gunakan nama property "Notifications" untuk akses di Repo, 
    // tapi arahkan ke Class "UserNotification"
    public virtual DbSet<UserNotification> Notifications { get; set; }

    public virtual DbSet<Competitor> Competitors { get; set; }
    public virtual DbSet<CompetitorPost> CompetitorPosts { get; set; }
    public virtual DbSet<ContentRecommendation> ContentRecommendations { get; set; }
    public virtual DbSet<Nich> Niches { get; set; }
    public virtual DbSet<SocialTrend> SocialTrends { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<SystemSetting> SystemSettings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Competitor>(entity =>
        {
            entity.ToTable("competitors");
            entity.Property(e => e.CompetitorId).HasColumnName("competitor_id");
            entity.Property(e => e.AccountHandle).IsRequired().HasColumnName("account_handle");
            entity.Property(e => e.LastScrapedAt).HasColumnType("DATETIME").HasColumnName("last_scraped_at");
            entity.Property(e => e.Platform).HasColumnName("platform");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.Competitors).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<CompetitorPost>(entity =>
        {
            entity.HasKey(e => e.PostId);
            entity.ToTable("competitor_posts");
            entity.Property(e => e.PostId).HasColumnName("post_id");
            entity.Property(e => e.CompetitorId).HasColumnName("competitor_id");
            entity.Property(e => e.EngagementRate).HasColumnName("engagement_rate");
            entity.Property(e => e.PostUrl).HasColumnName("post_url");
            entity.Property(e => e.PostedAt).HasColumnType("DATETIME").HasColumnName("posted_at");

            entity.HasOne(d => d.Competitor).WithMany(p => p.CompetitorPosts).HasForeignKey(d => d.CompetitorId);
        });

        modelBuilder.Entity<ContentRecommendation>(entity =>
        {
            entity.HasKey(e => e.RecommendationId);
            entity.ToTable("content_recommendations");
            entity.Property(e => e.RecommendationId).HasColumnName("recommendation_id");
            entity.Property(e => e.IsPremiumOnly).HasDefaultValue(false).HasColumnType("BOOLEAN").HasColumnName("is_premium_only");
            entity.Property(e => e.SuggestedCta).HasColumnName("suggested_cta");
            entity.Property(e => e.SuggestedHook).HasColumnName("suggested_hook");
            entity.Property(e => e.TrendId).HasColumnName("trend_id");

            entity.HasOne(d => d.Trend).WithMany(p => p.ContentRecommendations).HasForeignKey(d => d.TrendId);
        });

        modelBuilder.Entity<Nich>(entity =>
        {
            entity.HasKey(e => e.NicheId);
            entity.ToTable("niches");
            entity.HasIndex(e => e.NicheName, "IX_niches_niche_name").IsUnique();
            entity.Property(e => e.NicheId).HasColumnName("niche_id");
            entity.Property(e => e.NicheName).IsRequired().HasColumnName("niche_name");
        });

        // PERBAIKAN: Mapping untuk UserNotification
        modelBuilder.Entity<UserNotification>(entity =>
        {
            entity.HasKey(e => e.NotificationId);
            entity.ToTable("notifications");
            entity.Property(e => e.NotificationId).HasColumnName("notification_id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("DATETIME").HasColumnName("created_at");
            entity.Property(e => e.IsRead).HasDefaultValue(false).HasColumnType("BOOLEAN").HasColumnName("is_read");
            entity.Property(e => e.Message).HasColumnName("message");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithMany(p => p.Notifications).HasForeignKey(d => d.UserId);
        });

        modelBuilder.Entity<SocialTrend>(entity =>
        {
            entity.HasKey(e => e.TrendId);
            entity.ToTable("social_trends");
            entity.Property(e => e.TrendId).HasColumnName("trend_id");
            entity.Property(e => e.DiscoveredAt).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("DATETIME").HasColumnName("discovered_at");
            entity.Property(e => e.GrowthScore).HasColumnName("growth_score");
            entity.Property(e => e.IsViral).HasDefaultValue(false).HasColumnType("BOOLEAN").HasColumnName("is_viral");
            entity.Property(e => e.NicheId).HasColumnName("niche_id");
            entity.Property(e => e.Platform).HasColumnName("platform");
            entity.Property(e => e.TrendName).IsRequired().HasColumnName("trend_name");
            entity.Property(e => e.TrendType).HasColumnName("trend_type");
            entity.Property(e => e.SoundName).HasColumnName("sound_name");
            entity.Property(e => e.SoundUrl).HasColumnName("sound_url");

            entity.HasOne(d => d.Niche).WithMany(p => p.SocialTrends).HasForeignKey(d => d.NicheId);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.ToTable("users");
            entity.HasIndex(e => e.Email, "IX_users_email").IsUnique();
            entity.Property(e => e.UserId).HasColumnName("user_id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("DATETIME").HasColumnName("created_at");
            entity.Property(e => e.Email).IsRequired().HasColumnName("email");
            entity.Property(e => e.NicheId).HasColumnName("niche_id");
            entity.Property(e => e.PasswordHash).IsRequired().HasColumnName("password_hash");
            entity.Property(e => e.SubscriptionStatus).HasDefaultValue("Free").HasColumnName("subscription_status");
            entity.Property(e => e.Username).IsRequired().HasColumnName("username");

            entity.HasOne(d => d.Niche).WithMany(p => p.Users).HasForeignKey(d => d.NicheId);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}