// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Trend.MudWeb.Models;

public partial class UserNotification // Ganti nama di sini
{
    public int NotificationId { get; set; }
    public int UserId { get; set; }
    public string Message { get; set; } = "";
    public bool? IsRead { get; set; }
    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}