// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Trend.MudWeb.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public int? NicheId { get; set; }

    public string SubscriptionStatus { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Competitor> Competitors { get; set; } = new List<Competitor>();

    public virtual Nich Niche { get; set; }

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();
}